name: Publish to PyPI

on:
  push:
    tags:
      - "v*"  # Trigger only for tags starting with "v"

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update version in setup.cfg for build only
        run: |
          sed -i "s/^version = .*/version = ${{ env.VERSION }}/" setup.cfg
          cat setup.cfg


      - name: Update version in __init__.py
        run: |
          VERSION="${{ env.VERSION }}"
          MAJOR=$(echo "$VERSION" | awk -F. '{print $1}')
          MINOR=$(echo "$VERSION" | awk -F. '{print $2}')
          MICRO=$(echo "$VERSION" | awk -F. '{print $3}')

          sed -i "s/major=[0-9]\\+/major=$MAJOR/" src/pyosmogps/__init__.py
          sed -i "s/minor=[0-9]\\+/minor=$MINOR/" src/pyosmogps/__init__.py
          sed -i "s/micro=[0-9]\\+/micro=$MICRO/" src/pyosmogps/__init__.py
          sed -i "s/releaselevel=[^,]\\+/releaselevel='gh-action'/" src/pyosmogps/__init__.py
          cat src/pyosmogps/__init__.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
